#!/usr/bin/env node
/**
 * M2.14.2 demo:check — Demo <-> production snapshot gate.
 *
 * Validates that `frontend/src/lib/demo/demo_result.json` (generated by
 * `backend/scripts/generate_demo_fixture.py` from the real pipeline) is:
 *  - structurally sound (all required fields present, three periods, etc.)
 *  - consistent with the supported metric list
 *  - free of hand-crafted "low" confidence displays
 *  - covered by the four-language i18n keys it references (demo.*)
 *
 * Fails (exit code 1) when the snapshot drifts from the production contract,
 * so a new release cannot ship with a stale demo.
 */
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const fixturePath = join(root, "src", "lib", "demo", "demo_result.json");
const i18nPath = join(root, "src", "lib", "i18n.ts");

const errors = [];
const ok = (msg) => console.log(`  ✓ ${msg}`);
const fail = (msg) => errors.push(msg);

// ---------- load fixture ----------
if (!existsSync(fixturePath)) {
  console.error(`demo_result.json not found at ${fixturePath}`);
  process.exit(1);
}
const fixture = JSON.parse(readFileSync(fixturePath, "utf8"));

// ---------- structure ----------
const requiredTop = ["meta", "supported_metrics", "periods", "narrative"];
for (const k of requiredTop) {
  if (!(k in fixture)) fail(`fixture missing top-level key: ${k}`);
}
if (!Array.isArray(fixture.periods) || fixture.periods.length < 2) {
  fail(`fixture needs >= 2 periods for a meaningful cycle demo (got ${fixture.periods?.length ?? 0})`);
}
const metaKeys = ["schema_version", "engine_version", "health_score_engine", "generated_at", "source_commit", "data_md5"];
for (const k of metaKeys) {
  if (!fixture.meta?.[k]) fail(`fixture meta missing: ${k}`);
}
if (!/^[0-9a-f]{7,40}$/i.test(fixture.meta?.source_commit ?? "")) {
  fail(`fixture meta.source_commit is not a git sha: ${fixture.meta?.source_commit}`);
}

const SUPPORTED = new Set(fixture.supported_metrics ?? []);
const DISPLAY_METRICS = ["total_sales", "order_count", "average_order_value", "customer_count", "customer_concentration"];

for (const [i, period] of fixture.periods.entries()) {
  const tag = `periods[${i}]`;
  if (!period?.computed_metrics || !Array.isArray(period.computed_metrics)) {
    fail(`${tag} missing computed_metrics`);
    continue;
  }
  const names = new Set(period.computed_metrics.map((m) => m.metric_name));
  for (const want of [...SUPPORTED]) {
    if (!names.has(want)) fail(`${tag} missing supported metric: ${want}`);
  }
  for (const m of period.computed_metrics) {
    if (m.availability === "available" && m.confidence === "low") fail(`${tag} ${m.metric_name} is available but confidence=low (hand-crafted pessimism not allowed)`);
    if (!["available", "unavailable"].includes(m.availability)) fail(`${tag} ${m.metric_name} bad availability`);
    if (m.availability === "available" && m.value == null) fail(`${tag} ${m.metric_name} available but value null`);
  }
  const hs = period.health_score;
  if (!hs || hs.engine_version !== "health_score_v1") fail(`${tag} health_score engine mismatch`);
  if (!Array.isArray(hs.dimensions) || hs.dimensions.length === 0) fail(`${tag} health_score dimensions empty`);
  for (const dim of hs.dimensions) {
    if (dim.availability === "available" && dim.score == null) fail(`${tag} dim ${dim.name} available but score null`);
  }
  if (!period.key_metrics || period.key_metrics.length !== DISPLAY_METRICS.length) {
    fail(`${tag} key_metrics must have ${DISPLAY_METRICS.length} entries`);
  } else {
    const kmNames = period.key_metrics.map((k) => k.metric_name);
    if (JSON.stringify(kmNames) !== JSON.stringify(DISPLAY_METRICS)) fail(`${tag} key_metrics order mismatch`);
  }
}

// ---------- narrative ----------
const narrative = fixture.narrative;
if (!narrative) fail("narrative missing");
else {
  for (const kind of ["insights", "risks", "recommendations", "actions"]) {
    if (!Array.isArray(narrative[kind])) fail(`narrative.${kind} missing`);
  }
  if (!narrative.verification?.metric_changes || !Array.isArray(narrative.verification.metric_changes)) {
    fail("narrative.verification.metric_changes missing");
  }
  if (!narrative.memory?.intelligence) fail("narrative.memory.intelligence missing");
  if (!narrative.timeline || narrative.timeline.length !== fixture.periods.length) {
    fail("narrative.timeline must match period count");
  }
  // every action must carry i18n keys
  for (const a of narrative.actions ?? []) {
    if (!a.description_key) fail(`action ${a.id} missing description_key`);
  }
  // every open loop must carry a description key or be a production shape
  for (const loop of narrative.memory?.open_loops ?? []) {
    if (!loop.type) fail(`open loop missing type`);
  }
}

// ---------- i18n coverage ----------
let i18n = "";
if (existsSync(i18nPath)) i18n = readFileSync(i18nPath, "utf8");
function langBlockKeys(lang) {
  const marker = `const ${lang}: TranslationDict = {`;
  const start = i18n.indexOf(marker);
  if (start < 0) return [];
  const end = i18n.indexOf("\n};", start);
  const block = i18n.slice(start, end);
  const keys = new Set();
  for (const m of block.matchAll(/^  "([\w.]+)":/gm)) keys.add(m[1]);
  return keys;
}
const keySets = { zh: langBlockKeys("zh"), en: langBlockKeys("en"), ja: langBlockKeys("ja"), de: langBlockKeys("de") };
const langs = ["zh", "en", "ja", "de"];
for (const lang of langs) {
  if (keySets[lang].size === 0) fail(`i18n block missing for ${lang}`);
}

const referencedKeys = new Set();
function collect(obj) {
  if (!obj || typeof obj !== "object") return;
  if (Array.isArray(obj)) { obj.forEach(collect); return; }
  for (const [k, v] of Object.entries(obj)) {
    if (typeof v === "string" && /^demo\.[\w.]+$/.test(v)) referencedKeys.add(v);
    else collect(v);
  }
}
collect(fixture);

for (const key of [...referencedKeys].sort()) {
  for (const lang of langs) {
    if (!keySets[lang].has(key)) fail(`i18n missing ${key} in ${lang}`);
  }
}
const hardRequired = [
  "demo.period.label", "demo.health.summary", "demo.summary",
  "demo.insight.growthTitle", "demo.risk.pipelineTitle", "demo.rec.recovery.desc",
  "demo.verify.reason.aligned", "demo.loop.notExecuted", "demo.loop.longOpen",
  "demo.timeline.c1", "demo.schema.title", "demo.verification.title",
  "demo.ctaStartPrimary", "demo.ctaBackHome", "demo.fixtureNote",
];
for (const key of hardRequired) {
  for (const lang of langs) {
    if (!keySets[lang].has(key)) fail(`i18n missing required ${key} in ${lang}`);
  }
}

// ---------- summary ----------
if (errors.length > 0) {
  console.error("\ndemo:check FAILED");
  for (const e of errors) console.error(`  ✗ ${e}`);
  process.exit(1);
}
console.log(`demo:check PASS — fixture ${fixture.meta?.source_commit ?? "?"} · ${fixture.periods?.length ?? 0} periods · ${referencedKeys.size} i18n keys referenced`);
